import * as THREE from "https://unpkg.com/three@0.160.0/build/three.module.js";
const v=id("v"),o=id("o"),go=id("go"),s=id("s"),b=id("b"),c=id("c"),sceneHost=id("scene");
const hc=document.createElement("canvas"),hx=hc.getContext("2d",{willReadFrequently:true}),ox=o.getContext("2d");
let t=[],x=[],bpm=72,last=0;
const FACE=[10,67,109,338,297,151,50,101,118,117,123,147,280,330,347,346,352,376];
let fl=null,ready=false;
const r=new THREE.WebGLRenderer({antialias:true});r.setSize(sceneHost.clientWidth,sceneHost.clientHeight);sceneHost.appendChild(r.domElement);
const sc=new THREE.Scene();sc.background=new THREE.Color(0x060b11);const cam=new THREE.PerspectiveCamera(50,sceneHost.clientWidth/sceneHost.clientHeight,.1,100);cam.position.set(0,0.8,5.2);
sc.add(new THREE.AmbientLight(0x334055,.55));const dl=new THREE.DirectionalLight(0xff8ba0,1.1);dl.position.set(2,3,2);sc.add(dl);
const mat=new THREE.MeshStandardMaterial({color:0x9c2232,emissive:0x551018,emissiveIntensity:.25,roughness:.45});
const h=new THREE.Group();sc.add(h);h.add(mkSphere(.68,[-.2,-.1,0],[.95,1.22,.95]));h.add(mkSphere(.58,[.33,-.05,.05],[.95,1.1,.9]));const apex=new THREE.Mesh(new THREE.ConeGeometry(.47,1,40),mat);apex.position.set(-.05,-.95,0);apex.rotation.x=Math.PI;h.add(apex);
const ring=new THREE.Mesh(new THREE.RingGeometry(1.9,2.7,64),new THREE.MeshBasicMaterial({color:0xff5f73,transparent:true,opacity:.15,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false}));ring.rotation.x=Math.PI*.5;sc.add(ring);
function mkSphere(rad,pos,sca){const m=new THREE.Mesh(new THREE.SphereGeometry(rad,48,36),mat);m.position.set(...pos);m.scale.set(...sca);return m}
function id(x){return document.getElementById(x)}
function setS(m){s.textContent=m}
function env(p){if(p<.12)return Math.sin(p/.12*Math.PI*.5);if(p<.35)return 1-.6*((p-.12)/.23);if(p<.55){const u=(p-.35)/.2;return .4-.2*Math.sin(u*Math.PI)}const u=(p-.55)/.45;return .4*(1-u)-.05*Math.sin(u*Math.PI)}
function add(y,ts){x.push(y);t.push(ts);const cut=ts-10;while(t[0]<cut){t.shift();x.shift()}}
function est(){if(t.length<120)return null;const fs=30,t0=t[0],t1=t[t.length-1],n=Math.floor((t1-t0)*fs);if(n<120)return null;const u=[];let j=0;for(let i=0;i<n;i++){const tt=t0+i/fs;while(j<t.length-2&&t[j+1]<tt)j++;const a=(tt-t[j])/Math.max(1e-6,t[j+1]-t[j]);u[i]=x[j]+(x[j+1]-x[j])*a}
const m=u.reduce((a,b)=>a+b,0)/u.length;let z=u.map(v=>v-m),sd=Math.sqrt(z.reduce((a,b)=>a+b*b,0)/z.length)||1;z=z.map(v=>v/sd);const ma=(arr,w)=>arr.map((_,i)=>{let q=0,nn=0;for(let k=Math.max(0,i-w+1);k<=i;k++){q+=arr[k];nn++}return q/nn});const tr=ma(z,30);z=z.map((v,i)=>v-tr[i]);const sm=ma(z,3);const mm=sm.reduce((a,b)=>a+b,0)/sm.length;sd=Math.sqrt(sm.reduce((a,b)=>a+(b-mm)*(b-mm),0)/sm.length)||1;z=sm.map(v=>(v-mm)/sd);
const min=Math.floor((60/180)*fs),max=Math.floor((60/42)*fs),ac=[];for(let lag=min;lag<=max;lag++){let q=0,nn=0;for(let i=lag;i<z.length;i++){q+=z[i]*z[i-lag];nn++}ac.push(q/Math.max(1,nn))}
let bi=0;for(let i=1;i<ac.length;i++)if(ac[i]>ac[bi])bi=i;const lag=min+bi,hb=60*fs/lag,mean=ac.reduce((a,b)=>a+b,0)/ac.length,cr=(ac[bi]-mean)/(Math.abs(mean)+1e-6),cf=1/(1+Math.exp(-(cr-1.2)));return {bpm:hb,conf:cf}}
function rr(w,h){const rw=(w*.24)|0,rh=(h*.18)|0;return {x:((w-rw)/2)|0,y:(h*.18)|0,w:rw,h:rh}}
async function initFace(){try{const vision=await import("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/+esm");const fs=await vision.FilesetResolver.forVisionTasks("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm");fl=await vision.FaceLandmarker.createFromOptions(fs,{baseOptions:{modelAssetPath:"https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task"},runningMode:"VIDEO",numFaces:1});ready=true}catch{ready=false;setS("FaceMesh failed, fallback ROI")}}
function boxFromLm(lm,w,h){let minX=1,minY=1,maxX=0,maxY=0;for(const i of FACE){const p=lm[i];if(!p)continue;minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y)}if(maxX<=minX||maxY<=minY)return null;const x0=Math.max(0,Math.floor((minX-.06*(maxX-minX))*w)),y0=Math.max(0,Math.floor((minY-.06*(maxY-minY))*h)),x1=Math.min(w-1,Math.ceil((maxX+.06*(maxX-minX))*w)),y1=Math.min(h-1,Math.ceil((maxY+.06*(maxY-minY))*h));return {x:x0,y:y0,w:x1-x0,h:y1-y0}}
function gMean(r){const d=hx.getImageData(r.x,r.y,r.w,r.h).data;let g=0,n=0;for(let i=0;i<d.length;i+=16){g+=d[i+1];n++}return g/Math.max(1,n)}
go.onclick=async()=>{try{const st=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:640},height:{ideal:480}},audio:false});v.srcObject=st;await v.play();hc.width=v.videoWidth;hc.height=v.videoHeight;await initFace();setS("Running");requestAnimationFrame(loop)}catch(e){setS("Camera error: "+e.message)}};
function loop(ts){if(v.readyState>=2 && ts-last>33){last=ts;const w=hc.width,h=hc.height;hx.drawImage(v,0,0,w,h);let r1=rr(w,h);if(ready&&fl){const out=fl.detectForVideo(v,ts),lm=out.faceLandmarks&&out.faceLandmarks[0],bx=lm?boxFromLm(lm,w,h):null;if(bx)r1=bx}o.width=w;o.height=h;ox.clearRect(0,0,w,h);ox.strokeStyle="#8eea7d";ox.lineWidth=3;ox.strokeRect(r1.x,r1.y,r1.w,r1.h);
add(gMean(r1),ts*.001);const e=est();if(e){bpm=.82*bpm+.18*e.bpm;b.textContent=bpm.toFixed(1);c.textContent=Math.round(e.conf*100)+"%";setS(e.conf<.2?"Low confidence":"Live webcam BPM + 3D")}}
requestAnimationFrame(loop)}
let ph=0,lt=performance.now();function anim(nt){const dt=Math.min(.05,(nt-lt)/1000);lt=nt;ph=(ph+dt*(bpm/60))%1;const e=env(ph),stress=Math.max(0,Math.min(1,(bpm-60)/80)),v=1-(.10+.18*stress)*.6*e,w=1+(.10+.18*stress)*.25*e;h.children[0].scale.set(.95*w,1.22*v,.95*w);h.children[1].scale.set(.95*w,1.1*v,.9*w);h.children[2].scale.set(1,1-(.10+.18*stress)*.4*e,1);h.scale.setScalar(1.05+.05*e);h.rotation.y+=dt*.2;mat.emissiveIntensity=.25+.7*e;ring.material.opacity=.10+.45*e;ring.scale.setScalar(1+.2*e);r.render(sc,cam);requestAnimationFrame(anim)}requestAnimationFrame(anim);
addEventListener("resize",()=>{const w=sceneHost.clientWidth,h=sceneHost.clientHeight;r.setSize(w,h);cam.aspect=w/h;cam.updateProjectionMatrix()});
if(!navigator.mediaDevices?.getUserMedia){setS("No webcam API");go.disabled=true}